server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:~/restaurantdb
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  path: ./logs
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

